#!/usr/bin/env node
/* ============================================================
   Bagoasis (zzxdk) builder — designer bag showcase
   ------------------------------------------------------------
   Builds the Bagoasis catalog from the seller's Yupoo albums:
   each album = one bag. Grouped by bag TYPE (from its category),
   priced + model from the album title (P<price>-<model>), with
   cover + gallery photos downloaded locally (referer-locked, so
   every request sends the zzxdk Referer).

   Emits:
     assets/js/bago-catalog.js    -> var BAGO_RAW = [...]
     assets/js/bago-galleries.js  -> var BAGO_GALLERIES = {...}
     assets/img/bago/<albumId>/N.jpg
   Usage: node scripts/build-bago.js [--cap 6] [--size medium]
   ============================================================ */
const fs = require("fs");
const path = require("path");
const { execFileSync } = require("child_process");

const ROOT = path.resolve(__dirname, "..");
const OUT_CAT = path.join(ROOT, "assets/js/bago-catalog.js");
const OUT_GAL = path.join(ROOT, "assets/js/bago-galleries.js");
const IMG_DIR = path.join(ROOT, "assets/img/bago");
const ORIGIN = "https://zzxdk.x.yupoo.com";
const UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

const args = process.argv.slice(2);
const flag = (f) => { const i = args.indexOf(f); return i >= 0 ? args[i + 1] : null; };
const CAP = parseInt(flag("--cap"), 10) || 6;
const SIZE = flag("--size") || "medium";

/* Yupoo category id -> English bag type (from the live sidebar tree). */
const CATS = {
  "976343": "Messenger Bag", "976344": "Wallet", "976345": "Travel Bag", "976346": "Clutch",
  "976347": "Briefcase", "976348": "Shoulder Bag", "976349": "Tote Bag", "976352": "Crossbody Bag",
  "976354": "Box Bag", "976355": "Handbag", "976356": "Backpack",
  "982152": "Wallet", "982162": "Clutch", "982204": "Shoulder Bag", "982939": "Tote Bag",
  "982953": "Backpack", "983311": "Travel Bag",
};

const curl = (url, out) => {
  const a = ["-sSL", "-A", UA, "-H", `Referer: ${ORIGIN}/`, "--max-time", "40"];
  if (out) a.push("-o", out);
  a.push(url);
  return execFileSync("curl", a, out ? { stdio: "ignore" } : { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
};
const sleep = (ms) => execFileSync("sleep", [String(ms / 1000)]);

/* 1) collect albums across type categories: albumId -> {type, model, price} */
const albums = new Map();
for (const [cat, type] of Object.entries(CATS)) {
  let html = "";
  try { html = curl(`${ORIGIN}/categories/${cat}?isSubCate=true`); }
  catch (e) { console.log(`  ! cat ${cat} failed`); continue; }
  const re = /album__main[^>]*?title="([^"]*)"[^>]*?href="\/albums\/(\d+)/g;
  let m, n = 0;
  while ((m = re.exec(html))) {
    const title = m[1].trim(), id = m[2];
    if (albums.has(id)) continue;
    const pm = /P?\s*(\d{2,4})\s*[-_ ]\s*(\d{3,5})/i.exec(title);
    const price = pm ? parseInt(pm[1], 10) : null;
    const model = pm ? pm[2] : (title.match(/(\d{3,5})/) || [, null])[1];
    albums.set(id, { type, model, price, title });
    n++;
  }
  console.log(`  cat ${cat} (${type}): +${n} albums`);
  sleep(150);
}
console.log(`Unique albums: ${albums.size}`);

/* 2) per album: fetch page, grab photo hashes, download capped set */
const BAGO_RAW = [];
const BAGO_GALLERIES = {};
let idx = 0, dl = 0, fail = 0;
for (const [id, meta] of albums) {
  idx++;
  const dir = path.join(IMG_DIR, id);
  fs.mkdirSync(dir, { recursive: true });
  let hashes = [];
  try {
    const html = curl(`${ORIGIN}/albums/${id}?uid=1`);
    hashes = [...new Set((html.match(/photo\.yupoo\.com\/zzxdk\/[a-f0-9]+/g) || []).map((s) => s.split("/").pop()))].slice(0, CAP);
  } catch (e) { fail++; }
  const rel = [];
  hashes.forEach((h, i) => {
    const file = path.join(dir, `${i + 1}.jpg`);
    const relPath = `assets/img/bago/${id}/${i + 1}.jpg`;
    if (fs.existsSync(file) && fs.statSync(file).size > 2000) { rel.push(relPath); return; }
    try {
      curl(`https://photo.yupoo.com/zzxdk/${h}/${SIZE}.jpg`, file);
      if (fs.statSync(file).size > 2000) { rel.push(relPath); dl++; } else { fs.unlinkSync(file); }
    } catch (e) {}
    sleep(120);
  });
  if (!rel.length) { console.log(`  [${idx}/${albums.size}] album ${id}: no photos, skipped`); continue; }
  const name = `${meta.type}${meta.model ? " " + meta.model : ""}`;
  BAGO_RAW.push({
    id: `bago-${id}`, n: name, t: meta.type, p: meta.price,
    y: `${ORIGIN}/albums/${id}?uid=1`, im: rel[0],
  });
  BAGO_GALLERIES[`bago-${id}`] = rel;
  if (idx % 20 === 0) console.log(`  …${idx}/${albums.size} (downloaded ${dl})`);
  sleep(150);
}

/* 3) write outputs */
const banner = "/* Auto-generated by scripts/build-bago.js — Bagoasis (zzxdk) bag catalog. Do not hand-edit. */\n";
fs.writeFileSync(OUT_CAT, banner + "var BAGO_RAW = " + JSON.stringify(BAGO_RAW) + ";\n");
fs.writeFileSync(OUT_GAL, banner + "var BAGO_GALLERIES = " + JSON.stringify(BAGO_GALLERIES) + ";\n");
console.log(`\nDone. ${BAGO_RAW.length} bags, downloaded ${dl} photos, ${fail} album fails.`);
