#!/usr/bin/env node
/* ============================================================
   Yupoo gallery scraper — Momokicks
   ------------------------------------------------------------
   For every Momokick product that links to a Yupoo category,
   fetch that category's album covers (one photo per colourway),
   download a capped set locally, and emit assets/js/galleries.js
   as  MOMO_GALLERIES = { "<productId>": ["assets/img/.../1.jpg", …] }.

   Yupoo referer-locks its images, so every download sends a
   Referer header (that is the whole trick — without it you get
   an HTTP 567). Re-runnable: existing files are skipped.

   Usage:  node scripts/scrape-yupoo.js [--cap 8] [--size medium]
   ============================================================ */

const fs = require("fs");
const path = require("path");
const { execFileSync } = require("child_process");

const ROOT = path.resolve(__dirname, "..");
const CATALOG = path.join(ROOT, "assets/js/catalog-data.js");
const OUT_JS = path.join(ROOT, "assets/js/galleries.js");
const IMG_DIR = path.join(ROOT, "assets/img/momo/gallery");
const ORIGIN = "https://momokick.x.yupoo.com";
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

const args = process.argv.slice(2);
const CAP = num(flag("--cap"), 8); // max colourway covers per product
const SIZE = flag("--size") || "medium"; // small | medium | big
function flag(f) { const i = args.indexOf(f); return i >= 0 ? args[i + 1] : null; }
function num(v, d) { const n = parseInt(v, 10); return Number.isFinite(n) ? n : d; }

/* ---- load the catalog's raw momo array ---------------------- */
const src = fs.readFileSync(CATALOG, "utf8");
const sandbox = {};
new Function("g", src + "\ng.MOMO_RAW = typeof MOMO_RAW!=='undefined'?MOMO_RAW:[];")(sandbox);
const MOMO_RAW = sandbox.MOMO_RAW || [];

/* ---- map category id -> products, and keep product order ---- */
const catOf = (y) => { const m = /categories\/(\d+)/.exec(y || ""); return m ? m[1] : null; };
const byCat = new Map(); // catId -> [productId,…]
for (const r of MOMO_RAW) {
  const c = catOf(r.y);
  if (!c) continue;
  if (!byCat.has(c)) byCat.set(c, []);
  byCat.get(c).push(r.id);
}

console.log(`Products: ${MOMO_RAW.length} · categories to scrape: ${byCat.size} · cap ${CAP} · size ${SIZE}`);

/* ---- helpers ------------------------------------------------ */
function curl(url, outFile) {
  const a = ["-sS", "--fail", "-A", UA, "-H", `Referer: ${ORIGIN}/`, "--max-time", "40"];
  if (outFile) a.push("-o", outFile);
  a.push(url);
  return execFileSync("curl", a, outFile ? { stdio: "ignore" } : { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
}
const sleep = (ms) => execFileSync("sleep", [String(ms / 1000)]);

/* Extract ordered [albumId, coverHash] pairs from a category page. */
function coversFromHtml(html) {
  const re = /albums\/(\d+)[\s\S]*?photo\.yupoo\.com\/momokick\/([a-f0-9]+)\//g;
  const seen = new Set();
  const out = [];
  let m;
  while ((m = re.exec(html))) {
    if (seen.has(m[1])) continue;
    seen.add(m[1]);
    out.push(m[2]);
  }
  return out;
}

/* ---- scrape ------------------------------------------------- */
const galleries = {}; // productId -> [paths]
const catImages = {}; // catId -> [relPaths]
let catN = 0, dl = 0, skip = 0, fail = 0;

for (const [cat, productIds] of byCat) {
  catN++;
  const dir = path.join(IMG_DIR, cat);
  fs.mkdirSync(dir, { recursive: true });
  let hashes = [];
  try {
    const html = curl(`${ORIGIN}/categories/${cat}?isSubCate=true`);
    hashes = coversFromHtml(html).slice(0, CAP);
  } catch (e) {
    console.log(`  ! [${catN}/${byCat.size}] cat ${cat} page failed: ${e.message.split("\n")[0]}`);
  }
  const rel = [];
  hashes.forEach((h, i) => {
    const file = path.join(dir, `${i + 1}.jpg`);
    const relPath = `assets/img/momo/gallery/${cat}/${i + 1}.jpg`;
    if (fs.existsSync(file) && fs.statSync(file).size > 2000) { rel.push(relPath); skip++; return; }
    try {
      curl(`https://photo.yupoo.com/momokick/${h}/${SIZE}.jpg`, file);
      if (fs.statSync(file).size > 2000) { rel.push(relPath); dl++; }
      else { fs.unlinkSync(file); fail++; }
    } catch (e) { fail++; }
    sleep(120);
  });
  catImages[cat] = rel;
  console.log(`  [${catN}/${byCat.size}] cat ${cat}: ${rel.length} covers · ${productIds.length} product(s)`);
  sleep(200);
}

/* ---- assemble product galleries: own cover + colourway covers */
for (const r of MOMO_RAW) {
  const cat = catOf(r.y);
  const covers = (cat && catImages[cat]) || [];
  const list = [r.im, ...covers.filter((p) => p !== r.im)];
  // de-dup, cap at CAP+1 (hero + colourways)
  galleries[r.id] = [...new Set(list)].slice(0, CAP + 1);
}

/* ---- write galleries.js ------------------------------------- */
const banner =
  "/* Auto-generated by scripts/scrape-yupoo.js — Yupoo colourway galleries.\n" +
  "   Do not hand-edit; re-run the scraper to refresh. */\n";
fs.writeFileSync(OUT_JS, banner + "var MOMO_GALLERIES = " + JSON.stringify(galleries) + ";\n");

console.log(`\nDone. downloaded ${dl}, skipped ${skip}, failed ${fail}. Wrote ${OUT_JS}`);
